FROM debian:latest

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
                                   apt-get upgrade -y
RUN apt-get install -y curl gnupg

# Install node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs

# Create app directory
RUN mkdir -p /usr/src/framework
WORKDIR /usr/src/framework
# Bundle app source
COPY ./framework /usr/src/framework


# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
COPY ./client/package.json /usr/src/app/
RUN npm install
# Bundle app source
COPY ./client /usr/src/app

# Install app dependencies
RUN npm install
# Bundle app source
COPY ./ /usr/src/app

EXPOSE 8080
CMD [ "npm", "start" ]
