version: '1'
services:
  client:
    image: client:0.0.1
    container_name: clientCompose
    ports:
    - "8080:8080"
  server:
    image: server1:0.0.1
    container_name: serverCompose
    ports:
    - "5050:5050"
backend:
  frontend: